spring:
  application:
    name: chef-mgmt-backend
  profiles:
    active: local
  datasource:
    url: jdbc:postgresql://localhost:5432/chef_mgmt_db
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    open-in-view: false
  sql:
    init:
      mode: always
  rabbitmq:
    host: localhost
    port: 5672
server:
  port: 8777
  servlet:
    context-path: /api
app:
  jwt:
    secret: SD-2026-30434-SUPERCALIFRAGILISTICEXPIALIDOCIOUS
    expiration-minutes: 60
  security:
    login-url: /auth/v1/login
    allowed-urls: /auth/v1/logout,/swagger-ui/**,/swagger-ui.html,/v3/api-docs/**,/v3/api-docs.yaml,/error
chef-mgmt-mail:
  base-url: http://localhost:8888/api
  paths:
    base: /mails/v1
    chefs: /chefs
chef-mgmt:
  messaging:
    order-mail:
      queue: chef-mgmt.order-mail.queue
